name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build test
    runs-on: [self-hosted, linux, x64, gpu]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ğŸ›°ï¸ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ğŸ›©ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸšœ Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ğŸ›µ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸš Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: ğŸ›¸ Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: ğŸª‚ Lint
        run: pnpm lint

      - name: ğŸš€ Build
        run: pnpm build
        env:
          CI: true
          NODE_ENV: production
